<?php
// Include the processing file at the top
require_once 'php/listFilesProc.php';
?>

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Uploaded Files</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css">
</head>
<body class="p-4">

    <h1>Uploaded Files</h1>

    <!-- Display the list of files generated by listFilesProc.php -->
    <?php echo $output ?? '<p>No files to display.</p>'; ?>

    <!-- Optional link to go back to the upload page -->
    <a href="index.php" class="btn btn-secondary mt-3">Back to Upload</a>

</body>
</html>